name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"   # runs every 10 minutes
  workflow_dispatch:          # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl backend
        run: curl -s https://demo-backend-60xx.onrender.com/health || true
